game.ReplicatedStorage.Styles.Rush.VisualName.Value = "Kicker"
game.ReplicatedStorage.Styles.Rush.Color.Value = Color3.fromRGB(0, 240, 255)

game.ReplicatedStorage.Styles.Rush.Rush1.Value = "BEvadeStrikeLeft"
game.ReplicatedStorage.Styles.Rush.Rush2.Value = "BEvadeStrikeRight"
game.ReplicatedStorage.Styles.Rush.Rush3.Value = "RDashAttack"
game.ReplicatedStorage.Styles.Rush.Rush4.Value = "BAttack4"
game.ReplicatedStorage.Styles.Rush.Rush5.Value = "P_SAttack1"
game.ReplicatedStorage.Styles.Rush.Rush6.Value = "P_SAttack3"
game.ReplicatedStorage.Styles.Rush.Rush7.Value = "龍2Strike4"
game.ReplicatedStorage.Styles.Rush.Rush8.Value = "RStrike9"

game.ReplicatedStorage.Styles.Rush.Strike1.Value = "RStrike9"
game.ReplicatedStorage.Styles.Rush.Strike2.Value = "RSweep"
game.ReplicatedStorage.Styles.Rush.Strike3.Value = "P_SAttack3"
game.ReplicatedStorage.Styles.Rush.Strike4.Value = "龍2Strike4"
game.ReplicatedStorage.Styles.Rush.Strike5.Value = "RStrike9"
game.ReplicatedStorage.Styles.Rush.Strike6.Value = "RStrike9"
game.ReplicatedStorage.Styles.Rush.Strike7.Value = "RStrike9"
game.ReplicatedStorage.Styles.Rush.Strike8.Value = "RStrike9"
game.ReplicatedStorage.Styles.Rush.Strike9.Value = "RStrike9"
game.ReplicatedStorage.Styles.Rush.Grab.Value = "RSweep"
game.ReplicatedStorage.Styles.Rush.GrabStrike.Value = "T_CounterQuickstep"
game.ReplicatedStorage.Styles.Rush.Taunt.Value = "RushTaunt"
game.ReplicatedStorage.Styles.Rush.DashAttack.Value = "RDashAttack"