game.ReplicatedStorage.Styles.Rush.VisualName.Value = "Knife"
game.ReplicatedStorage.Styles.Rush.Color.Value = Color3.fromRGB(120, 0, 120)

game.ReplicatedStorage.Styles.Rush.Rush1.Value = "BAttack4"
game.ReplicatedStorage.Styles.Rush.Rush2.Value = "P_SStrike1"
game.ReplicatedStorage.Styles.Rush.Rush3.Value = "P_KAttack2"
game.ReplicatedStorage.Styles.Rush.Rush4.Value = "P_SAttack1"
game.ReplicatedStorage.Styles.Rush.Rush5.Value = "P_KAttack3"
game.ReplicatedStorage.Styles.Rush.Rush6.Value = "P_SAttack3"
game.ReplicatedStorage.Styles.Rush.Rush7.Value = "TonfaAttack3"
game.ReplicatedStorage.Styles.Rush.Rush8.Value = "龍2Strike4"

game.ReplicatedStorage.Styles.Rush.Strike1.Value = "龍2Strike4"
game.ReplicatedStorage.Styles.Rush.Strike2.Value = "BEvadeStrikeBack"
game.ReplicatedStorage.Styles.Rush.Strike3.Value = "龍2Strike4"
game.ReplicatedStorage.Styles.Rush.Strike4.Value = "B2Strike3"
game.ReplicatedStorage.Styles.Rush.Strike5.Value = "BEvadeStrikeLeft"
game.ReplicatedStorage.Styles.Rush.Strike6.Value = "P_SAttack1"
game.ReplicatedStorage.Styles.Rush.Strike7.Value = "P_SAttack3"
game.ReplicatedStorage.Styles.Rush.Strike8.Value = "BStrike4"
game.ReplicatedStorage.Styles.Rush.Strike9.Value = "BEvadeStrikeFront"
game.ReplicatedStorage.Styles.Rush.Grab.Value = "RSweep"
game.ReplicatedStorage.Styles.Rush.GrabStrike.Value = "T_CounterQuickstep"
game.ReplicatedStorage.Styles.Rush.Taunt.Value = "RushTaunt"
game.ReplicatedStorage.Styles.Rush.Taunt.AnimationId.Value = "rbxassetid://9313515166"
game.ReplicatedStorage.Styles.Rush.DashAttack.Value = "RStrike9"