game.ReplicatedStorage.Styles.Rush.VisualName.Value = "Koi"
game.ReplicatedStorage.Styles.Rush.Color.Value = Color3.fromRGB(10,50, 255)
--rush
game.ReplicatedStorage.Styles.Rush.Rush1.Value = "龍Attack1"
game.ReplicatedStorage.Styles.Rush.Rush2.Value = "BAttack2"
game.ReplicatedStorage.Styles.Rush.Rush3.Value = "龍Attack4"
game.ReplicatedStorage.Styles.Rush.Rush4.Value = "B2Strike2"
game.ReplicatedStorage.Styles.Rush.Rush5.Value = "BEvadeStrikeLeft"
game.ReplicatedStorage.Styles.Rush.Rush6.Value = "龍Attack4"
game.ReplicatedStorage.Styles.Rush.Rush7.Value = "BEvadeStrikeLeft"
game.ReplicatedStorage.Styles.Rush.Rush8.Value = "BAttack4"
--finstrike
game.ReplicatedStorage.Styles.Rush.Strike1.Value = "B2Strike1"
game.ReplicatedStorage.Styles.Rush.Strike2.Value = "BTStrike1"
game.ReplicatedStorage.Styles.Rush.Strike3.Value = "BTPunch2"
game.ReplicatedStorage.Styles.Rush.Strike4.Value = "B2Strike2"
game.ReplicatedStorage.Styles.Rush.Strike5.Value = "BEvadeStrikeLeft"
game.ReplicatedStorage.Styles.Rush.Strike6.Value = "RPunch7"
game.ReplicatedStorage.Styles.Rush.Strike7.Value = "RPunch7"
game.ReplicatedStorage.Styles.Rush.Strike8.Value = "RPunch7"
game.ReplicatedStorage.Styles.Rush.Strike9.Value = "RPunch7"
game.ReplicatedStorage.Styles.Rush.H_FallenDown.Value = "H_Whirl"
game.ReplicatedStorage.Styles.Rush.H_Fallen.Value = "H_FallenBeatdown"
game.ReplicatedStorage.Styles.Rush.Grab.Value = "B2Strike3"
game.ReplicatedStorage.Styles.Rush.Taunt.Value = "DragonTaunt"
game.ReplicatedStorage.Styles.Rush.DashAttack.Value = "B2Strike2"